name: Verify Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Secrets
      env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.EC2_PUBLIC_IP }}
          USER_NAME: ${{ secrets.EC2_USER_NAME }}
      run: |
          echo "EC2_PRIVATE_KEY length: ${#PRIVATE_KEY}"
          echo "EC2_HOST_NAME length: ${#HOST_NAME}"
          echo "EC2_USER_NAME length: ${#USER_NAME}"
